// apps/web/src/routes/auth/+page.svelte
<script lang="ts">
  import { goto } from '$app/navigation';
  import AuthPageShell from '$lib/components/AuthPageShell.svelte';

  let email = '';
  let otp = '';
  let busy = false;
  let error = '';
  let needsVerification = false;
  let emailSent: boolean | null = null;
  let warning = '';

  async function onRequestCode(event: SubmitEvent) {
    event.preventDefault();
    busy = true;
    error = '';
    needsVerification = false;
    emailSent = null;
    warning = '';
    otp = '';

    try {
      const resp = await fetch('/api/auth/request-email-otp', {
        method: 'POST',
        headers: { 'content-type': 'application/json' },
        body: JSON.stringify({ email })
      });
      const data = (await resp.json()) as { detail?: string; email_sent?: boolean; warning?: string | null };
      if (!resp.ok) throw new Error(data.detail || 'failed to request verification code');
      emailSent = Boolean(data.email_sent);
      warning = data.warning || '';
      needsVerification = true;
    } catch (err) {
      error = err instanceof Error ? err.message : 'unexpected error';
    } finally {
      busy = false;
    }
  }

  async function onVerifyCode() {
    busy = true;
    error = '';
    try {
      const resp = await fetch('/api/auth/verify-email-otp', {
        method: 'POST',
        headers: { 'content-type': 'application/json' },
        body: JSON.stringify({ email, otp })
      });
      const data = (await resp.json()) as { detail?: string };
      if (!resp.ok) throw new Error(data.detail || 'failed to verify code');
      await goto('/dashboard', { replaceState: true });
    } catch (err) {
      error = err instanceof Error ? err.message : 'unexpected error';
    } finally {
      busy = false;
    }
  }
</script>

<svelte:head><title>Sign In | Tahuna</title></svelte:head>

<AuthPageShell
  eyebrow="Account Access"
  title="Sign in or sign up"
  subtitle="Use your email and a one-time verification code. New and returning users use the same flow."
>
  <form on:submit={onRequestCode} class="space-y-5">
    <div class="space-y-2">
      <label for="email">Email</label>
      <input
        id="email"
        class="w-full rounded-md border border-input bg-background/60 px-3 py-2"
        type="email"
        autocomplete="email"
        required
        placeholder="you@example.com"
        bind:value={email}
      />
    </div>

    <button type="submit" disabled={busy || needsVerification} class="w-full sm:w-auto rounded-md border border-primary/50 bg-primary/15 px-4 py-2 text-sm">
      {busy ? 'Sending code...' : 'Send verification code'}
    </button>

    {#if error}<p class="text-sm text-destructive">{error}</p>{/if}

    {#if needsVerification}
      <div class="mt-4 rounded-lg border border-primary/40 bg-primary/10 p-4 space-y-3">
        <p class="text-sm text-foreground">Enter the 6-digit code sent to your email.</p>
        {#if emailSent}
          <p class="text-xs text-muted-foreground">Verification code sent to <span class="font-medium">{email}</span>.</p>
        {:else}
          <p class="text-xs text-amber-200">We could not confirm email delivery for <span class="font-medium">{email}</span>.{warning ? ` ${warning}` : ''}</p>
        {/if}

        <div class="space-y-3">
          <div class="space-y-2">
            <label for="otp">Verification Code</label>
            <input
              id="otp"
              class="w-full rounded-md border border-input bg-background/60 px-3 py-2"
              required
              inputmode="numeric"
              pattern="[0-9]{6}"
              maxlength="6"
              placeholder="123456"
              bind:value={otp}
            />
          </div>
          <button type="button" on:click={onVerifyCode} disabled={busy || otp.trim().length !== 6} class="w-full sm:w-auto rounded-md border border-primary/50 bg-primary/15 px-4 py-2 text-sm">
            {busy ? 'Verifying...' : 'Verify and continue'}
          </button>
        </div>
      </div>
    {/if}
  </form>
</AuthPageShell>

// web/app/auth/page.tsx
"use client"

import { useRouter } from "next/navigation"
import { useState, type FormEvent } from "react"
import { AuthPageShell } from "@/components/auth-page-shell"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"

export default function AuthPage() {
  const router = useRouter()
  const [email, setEmail] = useState("")
  const [otp, setOTP] = useState("")
  const [busy, setBusy] = useState(false)
  const [error, setError] = useState("")
  const [needsVerification, setNeedsVerification] = useState(false)

  async function onRequestCode(event: FormEvent<HTMLFormElement>) {
    event.preventDefault()
    setBusy(true)
    setError("")
    setNeedsVerification(false)
    setOTP("")

    try {
      const resp = await fetch("/api/auth/email-otp/send-verification-otp", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ email, type: "sign-in" }),
      })
      const data = (await resp.json()) as { detail?: string }
      if (!resp.ok) {
        throw new Error(data.detail || "failed to request verification code")
      }
      setNeedsVerification(true)
    } catch (err) {
      setError(err instanceof Error ? err.message : "unexpected error")
    } finally {
      setBusy(false)
    }
  }

  async function onVerifyCode() {
    setBusy(true)
    setError("")

    try {
      const verifyResp = await fetch("/api/auth/sign-in/email-otp", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          email,
          otp,
        }),
      })
      const verifyData = (await verifyResp.json()) as { detail?: string }
      if (!verifyResp.ok) {
        throw new Error(verifyData.detail || "failed to verify code")
      }
      router.replace("/dashboard")
    } catch (err) {
      setError(err instanceof Error ? err.message : "unexpected error")
    } finally {
      setBusy(false)
    }
  }

  return (
    <AuthPageShell
      eyebrow="Account Access"
      title="Sign in or sign up"
      subtitle="Use your email and a one-time verification code. New and returning users use the same flow."
    >
      <form onSubmit={onRequestCode} className="space-y-5">
        <div className="space-y-2">
          <Label htmlFor="email">Email</Label>
          <Input
            id="email"
            type="email"
            autoComplete="email"
            required
            placeholder="you@example.com"
            value={email}
            onChange={(event) => setEmail(event.target.value)}
          />
        </div>

        <Button type="submit" disabled={busy || needsVerification} className="w-full sm:w-auto">
          {busy ? "Sending code..." : "Send verification code"}
        </Button>

        {error ? <p className="text-sm text-destructive">{error}</p> : null}

        {needsVerification ? (
          <div className="mt-4 rounded-lg border border-primary/40 bg-primary/10 p-4 space-y-3">
            <p className="text-sm text-foreground">Enter the 6-digit code sent to your email.</p>
            <p className="text-xs text-muted-foreground">
              Verification code sent to <span className="font-medium">{email}</span>.
            </p>

            <div className="space-y-3">
              <div className="space-y-2">
                <Label htmlFor="otp">Verification Code</Label>
                <Input
                  id="otp"
                  required
                  inputMode="numeric"
                  pattern="[0-9]{6}"
                  maxLength={6}
                  placeholder="123456"
                  value={otp}
                  onChange={(event) => setOTP(event.target.value)}
                />
              </div>
              <Button type="button" onClick={onVerifyCode} disabled={busy || otp.trim().length !== 6} className="w-full sm:w-auto">
                {busy ? "Verifying..." : "Verify and continue"}
              </Button>
            </div>
          </div>
        ) : null}

      </form>
    </AuthPageShell>
  )
}
