// apps/web/src/routes/dashboard/+page.svelte
<script lang="ts">
  import { Alert } from "$lib/components/ui/alert";
  import { Badge } from "$lib/components/ui/badge";
  import { Button } from "$lib/components/ui/button";
  import { Input } from "$lib/components/ui/input";
  import { Label } from "$lib/components/ui/label";
  import { Select } from "$lib/components/ui/select";
  import {
    Table,
    TableBody,
    TableCell,
    TableHead,
    TableHeader,
    TableRow,
  } from "$lib/components/ui/table";
  import type { Catalog, Environment, MeResponse, Run } from "$lib/types";
  import {
    Database,
    Key,
    LogOut,
    Play,
    Server,
    Settings,
    Trash2,
  } from "lucide-svelte";
  import { onMount } from "svelte";

  type RunOverride = { gpu_type: string; gpu_count: string; volume_gb: string };
  type MainSection = "data" | "environments" | "runs";
  type UtilitySection = "settings";

  let me: MeResponse | null = null;
  let loading = true;
  let busy = false;
  let error = "";
  let message = "";

  let activeSection: MainSection | UtilitySection = "environments";

  let catalog: Catalog | null = null;
  let environments: Environment[] = [];
  let runs: Run[] = [];

  let envName = "Frontier Runtime";
  let envGPUType = "";
  let envGPUCount = "1";
  let envVolume = "120";
  let framework = "pt";
  let frameworkVersion = "";

  let runEnvID = "";
  let override: RunOverride = { gpu_type: "", gpu_count: "", volume_gb: "" };

  const primaryNav: {
    id: MainSection;
    label: string;
    icon: typeof Database;
  }[] = [
    { id: "data", label: "Data", icon: Database },
    { id: "environments", label: "Environments", icon: Server },
    { id: "runs", label: "Runs", icon: Play },
  ];

  $: frameworkVersions = catalog
    ? Object.keys(catalog.images[framework] || {})
    : [];
  $: if (
    frameworkVersions.length > 0 &&
    !frameworkVersions.includes(frameworkVersion)
  ) {
    frameworkVersion = frameworkVersions[0];
  }
  $: if (!runEnvID && environments.length > 0) {
    runEnvID = environments[0].environment_id;
  }
  $: selectedGPU = catalog?.gpus.find((g) => g.id === envGPUType) ?? null;
  $: maxGPUs = selectedGPU?.maxGpuCount || 8;
  $: if (Number.parseInt(envGPUCount, 10) > maxGPUs) {
    envGPUCount = String(maxGPUs);
  }
  $: selectedRunEnv =
    environments.find((e) => e.environment_id === runEnvID) ?? null;
  $: overrideGPU =
    catalog?.gpus.find((g) => g.id === override.gpu_type) ??
    (selectedRunEnv
      ? (catalog?.gpus.find((g) => g.id === selectedRunEnv.gpu_type) ?? null)
      : null);
  $: overrideMaxGPUs = overrideGPU?.maxGpuCount || 8;

  $: dataRows = [
    ...environments.map((env) => ({
      kind: "Environment artifacts",
      owner: env.environment_id,
      path: env.artifacts,
    })),
    ...runs.flatMap((run) => [
      { kind: "Run input", owner: run.run_id, path: run.input },
      { kind: "Run output", owner: run.run_id, path: run.output },
      { kind: "Run logs", owner: run.run_id, path: run.logs },
    ]),
  ];

  function statusTone(status: string): string {
    if (status === "running" || status === "provisioning")
      return "text-emerald-300 border-emerald-600/50 bg-emerald-900/20";
    if (status === "queued" || status === "cancelling")
      return "text-amber-200 border-amber-500/40 bg-amber-900/20";
    if (status === "succeeded" || status === "completed")
      return "text-cyan-200 border-cyan-500/40 bg-cyan-900/20";
    if (status === "failed" || status === "cancelled")
      return "text-rose-200 border-rose-500/40 bg-rose-900/20";
    return "text-foreground/90 border-border bg-card/80";
  }

  async function fetchJSON<T>(url: string, init?: RequestInit): Promise<T> {
    const resp = await fetch(url, init);
    const data = await resp.json();
    if (!resp.ok) throw new Error(data?.detail || "request failed");
    return data as T;
  }

  async function refreshData() {
    const [catalogData, envData, runData] = await Promise.all([
      fetchJSON<Catalog>("/api/dashboard/catalog"),
      fetchJSON<{ environments: Environment[] }>("/api/dashboard/environments"),
      fetchJSON<{ runs: Run[] }>("/api/dashboard/runs"),
    ]);

    catalog = catalogData;
    environments = envData.environments;
    runs = runData.runs;

    if (!envGPUType && catalogData.gpus.length > 0)
      envGPUType = catalogData.gpus[0].id;
  }

  async function withBusy(task: () => Promise<void>) {
    busy = true;
    error = "";
    message = "";
    try {
      await task();
    } catch (err) {
      error = err instanceof Error ? err.message : "unexpected error";
    } finally {
      busy = false;
    }
  }

  async function createEnvironment(event: SubmitEvent) {
    event.preventDefault();
    await withBusy(async () => {
      await fetchJSON<Environment>("/api/dashboard/environments", {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({
          name: envName,
          gpu_type: envGPUType,
          gpu_count: Number.parseInt(envGPUCount, 10),
          volume_gb: Number.parseInt(envVolume, 10),
          framework,
          version: frameworkVersion,
        }),
      });
      await refreshData();
      message = "Environment created.";
    });
  }

  async function deleteEnvironment(envID: string) {
    await withBusy(async () => {
      await fetchJSON(
        `/api/dashboard/environments?env_id=${encodeURIComponent(envID)}`,
        { method: "DELETE" },
      );
      await refreshData();
      message = `Environment ${envID} deleted.`;
    });
  }

  async function launchRun(event: SubmitEvent) {
    event.preventDefault();
    await withBusy(async () => {
      const payload: Record<string, string | number> = {
        environment_id: runEnvID,
      };
      if (override.gpu_type.trim()) payload.gpu_type = override.gpu_type.trim();
      if (override.gpu_count.trim())
        payload.gpu_count = Number.parseInt(override.gpu_count, 10);
      if (override.volume_gb.trim())
        payload.volume_gb = Number.parseInt(override.volume_gb, 10);

      await fetchJSON<Run>("/api/dashboard/runs", {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify(payload),
      });
      await refreshData();
      message = "Run launched.";
    });
  }

  async function cancelRun(runID: string) {
    await withBusy(async () => {
      await fetchJSON(
        `/api/dashboard/runs?run_id=${encodeURIComponent(runID)}`,
        { method: "DELETE" },
      );
      await refreshData();
      message = `Run ${runID} cancellation requested.`;
    });
  }

  async function logout() {
    await fetch("/api/auth/logout", { method: "POST" });
    window.location.href = "/auth";
  }

  onMount(async () => {
    try {
      const meResp = await fetch("/api/auth/me");
      if (meResp.status === 401) {
        window.location.href = "/auth";
        return;
      }
      if (!meResp.ok) throw new Error("failed to load session");
      me = (await meResp.json()) as MeResponse;
      await refreshData();
    } catch (err) {
      error = err instanceof Error ? err.message : "unexpected error";
    } finally {
      loading = false;
    }
  });
</script>

<svelte:head><title>Dashboard | Tahuna</title></svelte:head>

{#if loading}
  <div
    class="min-h-screen flex items-center justify-center text-sm text-foreground/70"
  >
    Loading dashboard…
  </div>
{:else}
  <div class="min-h-screen text-foreground bg-background">
    <!-- Sidebar -->
    <aside
      class="fixed inset-y-0 left-0 z-40 flex w-60 flex-col border-r border-border bg-background"
    >
      <div class="px-5 pt-6 pb-4">
        <p
          class="text-xs uppercase tracking-[0.2em] text-primary/90 font-semibold"
        >
          Tahuna
        </p>
        <p class="mt-1.5 text-sm text-foreground/60 truncate">{me?.email}</p>
      </div>

      <nav class="flex-1 px-3 space-y-0.5 overflow-y-auto">
        {#each primaryNav as item}
          <button
            type="button"
            class={`flex w-full items-center gap-3 rounded-lg px-3 py-2.5 text-sm font-medium transition-colors ${activeSection === item.id ? "bg-primary/10 text-primary" : "text-foreground/70 hover:bg-secondary/60 hover:text-foreground"}`}
            on:click={() => (activeSection = item.id)}
          >
            <svelte:component this={item.icon} class="h-4 w-4 shrink-0" />
            {item.label}
          </button>
        {/each}
      </nav>

      <div class="border-t border-border px-3 py-3 space-y-0.5">
        <a
          href="/api-key"
          class="flex w-full items-center gap-3 rounded-lg px-3 py-2.5 text-sm text-foreground/70 hover:bg-secondary/60 hover:text-foreground transition-colors"
        >
          <Key class="h-4 w-4 shrink-0" />
          API Key
        </a>
        <button
          type="button"
          class={`flex w-full items-center gap-3 rounded-lg px-3 py-2.5 text-sm font-medium transition-colors ${activeSection === "settings" ? "bg-primary/10 text-primary" : "text-foreground/70 hover:bg-secondary/60 hover:text-foreground"}`}
          on:click={() => (activeSection = "settings")}
        >
          <Settings class="h-4 w-4 shrink-0" />
          Settings
        </button>
        <button
          type="button"
          class="flex w-full items-center gap-3 rounded-lg px-3 py-2.5 text-sm text-rose-300/80 hover:bg-rose-900/20 hover:text-rose-200 transition-colors"
          on:click={logout}
        >
          <LogOut class="h-4 w-4 shrink-0" />
          Logout
        </button>
      </div>
    </aside>

    <!-- Main content -->
    <main class="ml-60 min-h-screen">
      <div class="px-8 py-8 max-w-6xl">
        {#if error}<Alert variant="destructive" className="mb-6">{error}</Alert
          >{/if}
        {#if message}<Alert variant="success" className="mb-6">{message}</Alert
          >{/if}

        <!-- DATA SECTION -->
        {#if activeSection === "data"}
          <section>
            <h2 class="text-2xl font-semibold tracking-tight mb-1">Data</h2>
            <p class="text-sm text-muted-foreground mb-8">
              Backend-backed storage references for environments and runs.
            </p>

            {#if dataRows.length === 0}
              <p class="text-sm text-muted-foreground py-12 text-center">
                No data assets yet. Create an environment or run first.
              </p>
            {:else}
              <div
                class="overflow-x-auto border border-border rounded-lg bg-card overflow-hidden"
              >
                <Table>
                  <TableHeader>
                    <TableRow className="border-border">
                      <TableHead>Type</TableHead>
                      <TableHead>Owner</TableHead>
                      <TableHead>Path</TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    {#each dataRows as row}
                      <TableRow>
                        <TableCell className="text-xs">{row.kind}</TableCell>
                        <TableCell className="font-mono text-xs"
                          >{row.owner}</TableCell
                        >
                        <TableCell className="font-mono text-xs"
                          >{row.path}</TableCell
                        >
                      </TableRow>
                    {/each}
                  </TableBody>
                </Table>
              </div>
            {/if}
          </section>
        {/if}

        <!-- ENVIRONMENTS SECTION -->
        {#if activeSection === "environments"}
          <section>
            <div class="flex items-center justify-between mb-8">
              <div>
                <h2 class="text-2xl font-semibold tracking-tight mb-1">
                  Environments
                </h2>
                <p class="text-sm text-muted-foreground">
                  GPU environments for training your models.
                </p>
              </div>
            </div>

            <!-- Create form -->
            <div class="border-b border-border pb-8 mb-8">
              <h3
                class="text-sm font-semibold uppercase tracking-widest text-muted-foreground mb-5"
              >
                Create Environment
              </h3>
              <form
                on:submit={createEnvironment}
                class="grid gap-4 lg:grid-cols-[1fr_1fr_1fr_1fr_auto] lg:items-end"
              >
                <div class="space-y-2">
                  <Label for="env-name">Name</Label>
                  <Input id="env-name" bind:value={envName} required />
                </div>
                <div class="space-y-2">
                  <Label for="gpu-type">GPU</Label>
                  <Select id="gpu-type" bind:value={envGPUType}>
                    {#each catalog?.gpus || [] as gpu}<option value={gpu.id}
                        >{gpu.displayName} ({gpu.memoryInGb}GB) · {gpu.maxGpuCount}
                        max</option
                      >{/each}
                  </Select>
                </div>
                <div class="space-y-2">
                  <Label for="framework">Framework</Label>
                  <Select id="framework" bind:value={framework}>
                    {#each Object.keys(catalog?.images || {}) as key}<option
                        value={key}>{key}</option
                      >{/each}
                  </Select>
                </div>
                <div class="grid grid-cols-3 gap-2">
                  <div class="space-y-2">
                    <Label for="version">Ver</Label>
                    <Select id="version" bind:value={frameworkVersion}>
                      {#each frameworkVersions as version}<option
                          value={version}>{version}</option
                        >{/each}
                    </Select>
                  </div>
                  <div class="space-y-2">
                    <Label for="gpu-count">Count</Label>
                    <Input
                      id="gpu-count"
                      type="number"
                      min="1"
                      max={maxGPUs}
                      placeholder="max {maxGPUs}"
                      bind:value={envGPUCount}
                    />
                  </div>
                  <div class="space-y-2">
                    <Label for="volume">Vol (GB)</Label>
                    <Input
                      id="volume"
                      type="number"
                      min="1"
                      bind:value={envVolume}
                    />
                  </div>
                </div>
                <Button type="submit" variant="secondary" disabled={busy}
                  >{busy ? "Saving…" : "Create"}</Button
                >
              </form>
            </div>

            <!-- Environment list -->
            {#if environments.length === 0}
              <p class="text-sm text-muted-foreground py-12 text-center">
                No environments yet.
              </p>
            {:else}
              <div
                class="overflow-x-auto border border-border rounded-lg bg-card overflow-hidden"
              >
                <Table>
                  <TableHeader>
                    <TableRow className="border-border">
                      <TableHead>Name</TableHead>
                      <TableHead>ID</TableHead>
                      <TableHead>Framework</TableHead>
                      <TableHead>GPU</TableHead>
                      <TableHead>Volume</TableHead>
                      <TableHead>Artifacts</TableHead>
                      <TableHead className="w-16"></TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    {#each environments as env}
                      <TableRow>
                        <TableCell className="font-medium">{env.name}</TableCell
                        >
                        <TableCell className="font-mono text-xs"
                          >{env.environment_id}</TableCell
                        >
                        <TableCell className="text-xs"
                          >{env.framework}:{env.version}</TableCell
                        >
                        <TableCell className="text-xs"
                          >{env.gpu_type} ×{env.gpu_count}</TableCell
                        >
                        <TableCell className="text-xs"
                          >{env.volume_gb} GB</TableCell
                        >
                        <TableCell
                          className="font-mono text-xs text-foreground/60"
                          >{env.artifacts}</TableCell
                        >
                        <TableCell>
                          <button
                            class="p-1.5 rounded-md text-foreground/40 hover:text-rose-300 hover:bg-rose-900/20 transition-colors disabled:opacity-30"
                            disabled={busy}
                            on:click={() =>
                              deleteEnvironment(env.environment_id)}
                            title="Delete environment"
                          >
                            <Trash2 class="h-3.5 w-3.5" />
                          </button>
                        </TableCell>
                      </TableRow>
                    {/each}
                  </TableBody>
                </Table>
              </div>
            {/if}
          </section>
        {/if}

        <!-- RUNS SECTION -->
        {#if activeSection === "runs"}
          <section>
            <div class="flex items-center justify-between mb-8">
              <div>
                <h2 class="text-2xl font-semibold tracking-tight mb-1">Runs</h2>
                <p class="text-sm text-muted-foreground">
                  Launch and monitor training runs.
                </p>
              </div>
              <Button
                variant="outline"
                on:click={() => withBusy(refreshData)}
                disabled={busy}
                size="sm">Refresh</Button
              >
            </div>

            <!-- Launch form -->
            <div class="border-b border-border pb-8 mb-8">
              <h3
                class="text-sm font-semibold uppercase tracking-widest text-muted-foreground mb-5"
              >
                Launch Run
              </h3>
              <form
                on:submit={launchRun}
                class="grid gap-4 lg:grid-cols-[1fr_1fr_auto_auto_auto] lg:items-end"
              >
                <div class="space-y-2">
                  <Label for="run-env">Environment</Label>
                  <Select id="run-env" bind:value={runEnvID}>
                    {#each environments as env}<option
                        value={env.environment_id}
                        >{env.name} ({env.environment_id})</option
                      >{/each}
                  </Select>
                </div>
                <div class="space-y-2">
                  <Label for="override-gpu">GPU Override</Label>
                  <Select id="override-gpu" bind:value={override.gpu_type}>
                    <option value=""
                      >Use env default ({selectedRunEnv?.gpu_type ||
                        "—"})</option
                    >
                    {#each catalog?.gpus || [] as gpu}<option value={gpu.id}
                        >{gpu.displayName} ({gpu.memoryInGb}GB) · {gpu.maxGpuCount}
                        max</option
                      >{/each}
                  </Select>
                </div>
                <div class="space-y-2">
                  <Label for="override-count">Count</Label>
                  <Input
                    id="override-count"
                    type="number"
                    min="1"
                    max={overrideMaxGPUs}
                    bind:value={override.gpu_count}
                    placeholder={selectedRunEnv?.gpu_count?.toString() || "—"}
                  />
                </div>
                <div class="space-y-2">
                  <Label for="override-volume">Vol</Label>
                  <Input
                    id="override-volume"
                    type="number"
                    min="1"
                    bind:value={override.volume_gb}
                    placeholder={selectedRunEnv?.volume_gb?.toString() || "—"}
                  />
                </div>
                <Button
                  type="submit"
                  variant="secondary"
                  disabled={busy || environments.length === 0}
                >
                  {busy ? "Starting…" : "Start run"}
                </Button>
              </form>
            </div>

            <!-- Run list -->
            {#if runs.length === 0}
              <p class="text-sm text-muted-foreground py-12 text-center">
                No runs yet.
              </p>
            {:else}
              <div
                class="overflow-x-auto border border-border rounded-lg bg-card overflow-hidden"
              >
                <Table>
                  <TableHeader>
                    <TableRow className="border-border">
                      <TableHead>Run</TableHead>
                      <TableHead>Status</TableHead>
                      <TableHead>Environment</TableHead>
                      <TableHead>Effective Infra</TableHead>
                      <TableHead className="w-20">Action</TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    {#each runs as run}
                      <TableRow className="align-top">
                        <TableCell className="font-mono text-xs"
                          >{run.run_id}</TableCell
                        >
                        <TableCell>
                          <Badge
                            variant="outline"
                            className={statusTone(run.status)}
                            >{run.status}</Badge
                          >
                        </TableCell>
                        <TableCell className="font-mono text-xs"
                          >{run.env_id}</TableCell
                        >
                        <TableCell className="text-xs text-foreground/80">
                          {run.effective_gpu_type || "—"} / {run.effective_gpu_count ||
                            "—"} / {run.effective_volume_gb || "—"}GB
                        </TableCell>
                        <TableCell>
                          <Button
                            size="sm"
                            variant="outline"
                            disabled={busy ||
                              ![
                                "queued",
                                "provisioning",
                                "running",
                                "cancelling",
                              ].includes(run.status)}
                            on:click={() => cancelRun(run.run_id)}
                          >
                            Cancel
                          </Button>
                        </TableCell>
                      </TableRow>
                    {/each}
                  </TableBody>
                </Table>
              </div>
            {/if}
          </section>
        {/if}

        <!-- SETTINGS SECTION -->
        {#if activeSection === "settings"}
          <section>
            <h2 class="text-2xl font-semibold tracking-tight mb-1">Settings</h2>
            <p class="text-sm text-muted-foreground mb-8">
              Account and dashboard controls.
            </p>

            <div class="space-y-6 max-w-lg">
              <div class="border-b border-border pb-4">
                <p
                  class="text-xs uppercase tracking-widest text-muted-foreground mb-1"
                >
                  Email
                </p>
                <p class="font-medium">{me?.email}</p>
              </div>
              <div class="border-b border-border pb-4">
                <p
                  class="text-xs uppercase tracking-widest text-muted-foreground mb-1"
                >
                  User ID
                </p>
                <p class="font-mono text-sm">{me?.user_id}</p>
              </div>
              <div class="flex flex-wrap gap-3 pt-2">
                <a href="/api-key"
                  ><Button variant="secondary">Manage API Key</Button></a
                >
                <Button
                  variant="outline"
                  on:click={() => withBusy(refreshData)}
                  disabled={busy}>Sync from backend</Button
                >
              </div>
            </div>
          </section>
        {/if}
      </div>
    </main>
  </div>
{/if}

// web/app/dashboard/page.tsx
"use client"

import { MachineSelector } from "@/components/machine-selector"
import { SectionHeading } from "@/components/section-heading"
import { Badge, statusVariant } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Select } from "@/components/ui/select"
import { PageLoader } from "@/components/ui/spinner"
import { api } from "@/convex/_generated/api"
import { authClient } from "@/lib/auth-client"
import { useAction, useConvexAuth, useMutation, useQuery } from "convex/react"
import { Database, Key, LogOut, Play, Server, Settings, Trash2 } from "lucide-react"
import Link from "next/link"
import { useRouter } from "next/navigation"
import { useEffect, useMemo, useState, type FormEvent } from "react"

type MainSection = "data" | "environments" | "runs"
type UtilitySection = "settings"

type GPUInfo = { id: string; displayName: string; memoryInGb: number; maxGpuCount: number; pricePerHour?: number | null }

export default function DashboardPage() {
  const router = useRouter()
  const { isAuthenticated, isLoading: authLoading } = useConvexAuth()

  const [busy, setBusy] = useState(false)
  const [error, setError] = useState("")
  const [message, setMessage] = useState("")

  const [activeSection, setActiveSection] = useState<MainSection | UtilitySection>("environments")

  const [explicitEnvGPUType, setExplicitEnvGPUType] = useState("")
  const [explicitEnvGPUCount, setExplicitEnvGPUCount] = useState("")
  const [selectedImageKey, setSelectedImageKey] = useState("")

  const primaryNav: { id: MainSection; label: string; icon: typeof Database }[] = [
    { id: "data", label: "Data", icon: Database },
    { id: "environments", label: "Environments", icon: Server },
    { id: "runs", label: "Runs", icon: Play },
  ]

  const catalog = useQuery(api.catalog.getCatalog)
  const getDynamicGpus = useAction(api.catalog.getDynamicGpus)
  const currentUser = useQuery(api.auth.getCurrentUser)
  const envResult = useQuery(api.environments.list)
  const runResult = useQuery(api.runs.list)

  const [dynamicGpus, setDynamicGpus] = useState<GPUInfo[]>([])
  const [loadingGpus, setLoadingGpus] = useState(true)

  useEffect(() => {
    async function fetchGpus() {
      try {
        setLoadingGpus(true)
        const gpus = await getDynamicGpus()
        setDynamicGpus(gpus)
      } catch (err) {
        console.error("Failed to fetch dynamic gpus", err)
      } finally {
        setLoadingGpus(false)
      }
    }

    if (isAuthenticated) {
      fetchGpus()
    }
  }, [getDynamicGpus, isAuthenticated])

  const environments = envResult?.environments ?? []
  const runs = runResult?.runs ?? []

  const createEnvMutation = useMutation(api.environments.create)
  const removeEnvMutation = useMutation(api.environments.remove)
  const createRunMutation = useMutation(api.runs.create)
  const removeRunMutation = useMutation(api.runs.remove)

  const frameworkOptions = useMemo(() => {
    if (!catalog) return []

    return Object.entries(catalog.images).flatMap(([framework, versions]) =>
      Object.keys(versions).map((version) => ({
        key: `${framework}:${version}`,
        framework,
        version,
        label: `${framework.toUpperCase()} ${version}`,
      })),
    )
  }, [catalog])

  const currentGpusList = dynamicGpus
  const envGPUType = explicitEnvGPUType || (currentGpusList.length ? currentGpusList[0].id : "")

  const selectedGPU = useMemo(() => {
    return currentGpusList.find((g) => g.id === envGPUType) ?? null
  }, [currentGpusList, envGPUType])

  const maxGPUs = selectedGPU?.maxGpuCount || 8
  const rawGPUCount = explicitEnvGPUCount || "1"
  const envGPUCountValidation = Number.parseInt(rawGPUCount, 10)
  const envGPUCount = envGPUCountValidation > maxGPUs ? String(maxGPUs) : rawGPUCount

  const imageSelection = useMemo(() => {
    return frameworkOptions.find((option) => option.key === selectedImageKey) ?? frameworkOptions[0] ?? null
  }, [frameworkOptions, selectedImageKey])

  const environmentName = useMemo(() => {
    const machineLabel = selectedGPU?.displayName ?? "Training"
    const frameworkLabel = imageSelection?.label ?? "Environment"
    return `${machineLabel} · ${frameworkLabel}`
  }, [imageSelection, selectedGPU])

  const dataRows = useMemo(() => {
    return [
      ...environments.map((env) => ({
        kind: "Environment artifacts",
        owner: env.environment_id,
        path: env.artifacts,
      })),
      ...runs.flatMap((run) => [
        { kind: "Run input", owner: run.run_id, path: run.input },
        { kind: "Run output", owner: run.run_id, path: run.output },
        { kind: "Run logs", owner: run.run_id, path: run.logs },
      ]),
    ]
  }, [environments, runs])

  const userEmail = currentUser?.email ?? ""

  async function withBusy(task: () => Promise<void>) {
    setBusy(true)
    setError("")
    setMessage("")
    try {
      await task()
    } catch (err) {
      setError(err instanceof Error ? err.message : "unexpected error")
    } finally {
      setBusy(false)
    }
  }

  async function createEnvironment(event: FormEvent<HTMLFormElement>) {
    event.preventDefault()
    await withBusy(async () => {
      await createEnvMutation({
        name: environmentName,
        gpu_type: envGPUType,
        gpu_count: Number.parseInt(envGPUCount, 10),
        volume_gb: 120,
        framework: imageSelection?.framework ?? "pt",
        version: imageSelection?.version ?? "",
      })
      setMessage("Environment created.")
    })
  }

  async function deleteEnvironment(envID: string) {
    await withBusy(async () => {
      await removeEnvMutation({ environmentId: envID as any })
      setMessage(`Environment ${envID} deleted.`)
    })
  }

  async function launchRun(envID: string) {
    await withBusy(async () => {
      await createRunMutation({ environmentId: envID as any })
      setMessage("Run launched.")
    })
  }

  async function cancelRun(runID: string) {
    await withBusy(async () => {
      await removeRunMutation({ runId: runID as any })
      setMessage(`Run ${runID} cancellation requested.`)
    })
  }

  async function logout() {
    await authClient.signOut()
    router.replace("/auth")
  }

  if (authLoading || !isAuthenticated) {
    return <PageLoader message="Loading dashboard…" />
  }

  return (
    <div className="min-h-screen text-foreground bg-background">
      <aside className="fixed inset-y-0 left-0 z-40 flex w-64 flex-col border-r border-border bg-background">
        <div className="px-5 pt-7 pb-5">
          <p className="text-xs uppercase tracking-[0.2em] text-primary/90 font-semibold">Tahuna</p>
          <p className="mt-1.5 text-sm text-muted-foreground truncate">{userEmail}</p>
        </div>

        <nav className="flex-1 px-4 space-y-1 overflow-y-auto">
          {primaryNav.map((item) => {
            const Icon = item.icon
            const active = activeSection === item.id
            return (
              <Button
                key={item.id}
                variant={active ? "sidebar-active" : "sidebar"}
                onClick={() => setActiveSection(item.id)}
              >
                <Icon className="h-4 w-4 shrink-0" />
                {item.label}
              </Button>
            )
          })}
        </nav>

        <div className="border-t border-border px-4 py-4 space-y-1">
          <Button variant="sidebar" asChild>
            <Link href="/api-key">
              <Key className="h-4 w-4 shrink-0" />
              API Key
            </Link>
          </Button>
          <Button
            variant={activeSection === "settings" ? "sidebar-active" : "sidebar"}
            onClick={() => setActiveSection("settings")}
          >
            <Settings className="h-4 w-4 shrink-0" />
            Settings
          </Button>
          <Button
            variant="sidebar-danger"
            onClick={logout}
          >
            <LogOut className="h-4 w-4 shrink-0" />
            Logout
          </Button>
        </div>
      </aside>

      <main className="ml-64 min-h-screen">
        <div className="px-10 py-10 max-w-6xl">
          {error ? <p className="mb-6 rounded-md border border-destructive/60 bg-destructive/10 px-4 py-3 text-sm text-destructive">{error}</p> : null}
          {message ? <p className="mb-6 rounded-md border border-primary/50 bg-primary/10 px-4 py-3 text-sm text-primary">{message}</p> : null}

          {activeSection === "data" ? (
            <section>
              <SectionHeading variant="medium" className="mb-2">Data</SectionHeading>
              <p className="text-base text-muted-foreground mb-10">Backend-backed storage references for environments and runs.</p>

              {dataRows.length === 0 ? (
                <p className="text-sm text-muted-foreground py-12 text-center">No data assets yet. Create an environment or run first.</p>
              ) : (
                <Card className="overflow-hidden">
                  <table className="w-full text-sm">
                    <thead>
                      <tr className="border-b border-border text-left">
                        <th className="px-4 py-3 text-sm font-medium text-muted-foreground">Type</th>
                        <th className="px-4 py-3 text-sm font-medium text-muted-foreground">Owner</th>
                        <th className="px-4 py-3 text-sm font-medium text-muted-foreground">Path</th>
                      </tr>
                    </thead>
                    <tbody>
                      {dataRows.map((row) => (
                        <tr key={`${row.kind}-${row.owner}-${row.path}`} className="border-b last:border-b-0 border-border/40">
                          <td className="px-4 py-3 text-sm">{row.kind}</td>
                          <td className="px-4 py-3 font-mono text-xs">{row.owner}</td>
                          <td className="px-4 py-3 font-mono text-xs">{row.path}</td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </Card>
              )}
            </section>
          ) : null}

          {activeSection === "environments" ? (
            <section className="space-y-8">
              <div>
                <SectionHeading variant="medium" className="mb-2">Environments</SectionHeading>
                <p className="text-base text-muted-foreground">Create and manage your GPU-backed training environments.</p>
              </div>

              <Card className="p-6">
                <form onSubmit={createEnvironment} className="space-y-6">
                  <MachineSelector
                    machines={currentGpusList}
                    value={envGPUType}
                    loading={loadingGpus}
                    onChange={setExplicitEnvGPUType}
                    disabled={currentGpusList.length === 0 && !loadingGpus}
                  />

                  <div className="grid gap-3 xl:grid-cols-2 md:grid-cols-2">
                    <div className="space-y-2">
                      <Label htmlFor="framework">Framework</Label>
                      <Select
                        id="framework"
                        value={imageSelection?.key ?? ""}
                        onChange={(event) => setSelectedImageKey(event.target.value)}
                      >
                        {frameworkOptions.map((option) => (
                          <option key={option.key} value={option.key}>{option.label}</option>
                        ))}
                      </Select>
                    </div>
                    <div className="space-y-2">
                      <Label htmlFor="gpu-count">GPU Count</Label>
                      <Input
                        id="gpu-count"
                        type="number"
                        min={1}
                        max={maxGPUs}
                        value={envGPUCount}
                        onChange={(event) => setExplicitEnvGPUCount(event.target.value)}
                      />
                      {selectedGPU ? <p className="text-xs text-muted-foreground">Max for this machine: {selectedGPU.maxGpuCount}</p> : null}
                    </div>
                  </div>

                  <Button type="submit" disabled={busy || currentGpusList.length === 0 || !imageSelection}>
                    {busy ? "Saving..." : "Create environment"}
                  </Button>
                </form>
              </Card>

              {environments.length === 0 ? (
                <p className="text-sm text-muted-foreground">No environments yet.</p>
              ) : (
                <Card className="overflow-hidden">
                  <table className="w-full text-sm">
                    <thead>
                      <tr className="border-b border-border text-left">
                        <th className="px-4 py-3 text-sm font-medium text-muted-foreground">ID</th>
                        <th className="px-4 py-3 text-sm font-medium text-muted-foreground">Name</th>
                        <th className="px-4 py-3 text-sm font-medium text-muted-foreground">Spec</th>
                        <th className="px-4 py-3 text-sm font-medium text-muted-foreground">Actions</th>
                      </tr>
                    </thead>
                    <tbody>
                      {environments.map((env) => (
                        <tr key={env.environment_id} className="border-b last:border-b-0 border-border/40">
                          <td className="px-4 py-3 font-mono text-xs">{env.environment_id}</td>
                          <td className="px-4 py-3 text-sm">{env.name}</td>
                          <td className="px-4 py-3 text-sm text-muted-foreground">{env.framework}:{env.version} | {env.gpu_type} x{env.gpu_count} | {env.volume_gb}GB</td>
                          <td className="px-4 py-3">
                            <div className="flex items-center gap-2">
                              <Button variant="outline" size="sm" onClick={() => launchRun(env.environment_id)} disabled={busy}>
                                <Play className="h-3.5 w-3.5" />
                                Run
                              </Button>
                              <Button variant="outline" size="sm" onClick={() => deleteEnvironment(env.environment_id)} disabled={busy}>
                                <Trash2 className="h-3.5 w-3.5" />
                              </Button>
                            </div>
                          </td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </Card>
              )}
            </section>
          ) : null}

          {activeSection === "runs" ? (
            <section>
              <SectionHeading variant="medium" className="mb-2">Runs</SectionHeading>
              <p className="text-base text-muted-foreground mb-10">Monitor your training runs. Launch a run from an environment.</p>

              {environments.length === 0 ? (
                <p className="text-sm text-muted-foreground py-12 text-center">Create an environment first to launch runs.</p>
              ) : runs.length === 0 ? (
                <p className="text-sm text-muted-foreground py-12 text-center">No runs yet. Go to Environments and hit Run to start one.</p>
              ) : (
                <Card className="overflow-hidden">
                  <table className="w-full text-sm">
                    <thead>
                      <tr className="border-b border-border text-left">
                        <th className="px-4 py-3 text-sm font-medium text-muted-foreground">Run</th>
                        <th className="px-4 py-3 text-sm font-medium text-muted-foreground">Status</th>
                        <th className="px-4 py-3 text-sm font-medium text-muted-foreground">Environment</th>
                        <th className="px-4 py-3 text-sm font-medium text-muted-foreground">Effective Infra</th>
                        <th className="px-4 py-3 text-sm font-medium text-muted-foreground">Actions</th>
                      </tr>
                    </thead>
                    <tbody>
                      {runs.map((run) => (
                        <tr key={run.run_id} className="border-b last:border-b-0 border-border/40 align-top">
                          <td className="px-4 py-3 font-mono text-xs">{run.run_id}</td>
                          <td className="px-4 py-3">
                            <Badge variant={statusVariant(run.status)}>{run.status}</Badge>
                          </td>
                          <td className="px-4 py-3 font-mono text-xs">{run.env_id}</td>
                          <td className="px-4 py-3 text-sm text-muted-foreground">{run.effective_gpu_type || "-"} / {run.effective_gpu_count || "-"} / {run.effective_volume_gb || "-"}GB</td>
                          <td className="px-4 py-3">
                            <Button
                              variant="outline"
                              size="sm"
                              disabled={busy || !["queued", "provisioning", "running", "cancelling"].includes(run.status)}
                              onClick={() => cancelRun(run.run_id)}
                            >
                              <Trash2 className="h-3.5 w-3.5" />
                              Cancel
                            </Button>
                          </td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </Card>
              )}
            </section>
          ) : null}

          {activeSection === "settings" ? (
            <section>
              <SectionHeading variant="medium" className="mb-2">Settings</SectionHeading>
              <p className="text-base text-muted-foreground">Account and dashboard controls.</p>
            </section>
          ) : null}
        </div>
      </main>
    </div>
  )
}
